FinanceManagementApp/urls.py
# urls.py
from django.urls import path

from .views.transactions import AllTransactionsView
from .views.dashboard import DashboardView
from .views.reports import ReportsView

urlpatterns = [
    path("", DashboardView.as_view(), name=""),
    path("transactions/", AllTransactionsView.as_view(), name="transactions"),
    path("reports/", ReportsView.as_view(), name="reports"),
]

FinanceManagementProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("FinanceManagementApp.urls")),
]

FinanceManagementApp/models/Project.py
from django.db import models
from django.db.models.constraints import CheckConstraint
from django.db.models.expressions import Q
from django.core.exceptions import ValidationError


# Project model
class Project(models.Model):
    PROJECT_STATUS = [
        ("upcoming", "UPCOMING"),
        ("ongoing", "ONGOING"),
        ("completed", "COMPLETED"),
    ]
    status = models.CharField(max_length=10, choices=PROJECT_STATUS)
    name = models.CharField(max_length=50)

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} : {self.status}"

    # Custom validations
    def clean(self):
        if self.start_date and self.end_date and self.end_date < self.start_date:
            raise ValidationError("End date cannot be less than start date")

        if self.status == "completed" and not self.end_date:
            raise ValidationError(
                {"end_date": "End date is required when project status is complete"}
            )

        if self.status != "completed" and self.end_date:
            raise ValidationError(
                {
                    "end_date": "End date should be null when project status is not complete"
                }
            )

    class Meta:
        constraints = [
            CheckConstraint(
                check=Q(end_date__gte=models.F("start_date")),
                name="end_date_after_start_date",
            )
        ]

FinanceManagementApp/models/Transaction.py
from django.db import models
from django.core.exceptions import ValidationError


# Transaction model
class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ("Income", "Income"),
        ("Expense", "Expense"),
    ]
    EXPENSE_TYPES = [
        ("Office Supplies", "Office Supplies"),
        ("Travel", "Travel"),
        ("Utilities", "Utilities"),
        ("Salary", "Salary"),
        ("Miscellaneous", "Miscellaneous"),
        ("GST", "GST"),
        ("GeM", "GeM"),
        ("ESI", "ESI"),
    ]
    INCOME_TYPES = [
        ("Cash", "Cash"),
        ("Digital", "Digital"),
        ("Cheque", "Cheque"),
    ]
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPES)
    income_expense_type = models.CharField(
        max_length=15, choices=INCOME_TYPES + EXPENSE_TYPES, null=True, blank=True
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    description = models.TextField(null=True, blank=True)

    # Return a string representation of the transaction.
    def __str__(self):
        return f"{self.transaction_type} : {self.amount}"

    # Validate the transaction before saving.
    def clean(self):
        if self.transaction_type == "Expense":
            if self.income_expense_type not in [t[0] for t in self.EXPENSE_TYPES]:
                raise ValidationError("Expense type cannot be Cash/Digital/Cheque")
        elif self.transaction_type == "Income":
            if self.income_expense_type not in [t[0] for t in self.INCOME_TYPES]:
                raise ValidationError("Income type can only be Cash/Digital/Cheque")

AccountsManagementApp/views/dashboard.py
# views.py
from datetime import datetime, timedelta
from django.shortcuts import render
from django.views import View
from dateutil.relativedelta import relativedelta
from django.db.models import Sum
from AccountsManagementApp.models.Transaction import Transaction


class DashboardView(View):
    def post(self, request):
        pass

    def get(self, request):
        # Fetch the 10 most recent transactions
        recent_transactions = Transaction.objects.select_related("project").order_by(
            "-date"
        )[:10]

        this_month_start = datetime.now().replace(day=1)
        this_month_end = (datetime.now() + relativedelta(months=1)).replace(
            day=1
        ) - timedelta(days=1)

        current_date = datetime.now()
        if current_date.month < 4:
            this_year_start = (current_date - relativedelta(years=1)).replace(
                month=4, day=1
            )
            this_year_end = current_date.replace(month=3, day=31)
        else:
            this_year_start = current_date.replace(month=4, day=1)
            this_year_end = (current_date + relativedelta(years=1)).replace(
                month=3, day=31
            )

        revenue_this_month = (
            Transaction.objects.filter(
                date__gte=this_month_start,
                date__lte=this_month_end,
                transaction_type="Income",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )

        expense_this_month = (
            Transaction.objects.filter(
                date__gte=this_month_start,
                date__lte=this_month_end,
                transaction_type="Expense",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )

        revenue_this_year = (
            Transaction.objects.filter(
                date__gte=this_year_start,
                date__lte=this_year_end,
                transaction_type="Income",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )

        expense_this_year = (
            Transaction.objects.filter(
                date__gte=this_year_start,
                date__lte=this_year_end,
                transaction_type="Expense",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )

        return render(
            request,
            "AccountsManagementApp/dashboard.html",
            {
                "revenue_this_month": revenue_this_month,
                "expense_this_month": expense_this_month,
                "revenue_this_year": revenue_this_year,
                "expense_this_year": expense_this_year,
                "recent_transactions": recent_transactions,
            },
        )

AccountsManagementApp/views/reports.py
from django.shortcuts import render
from django.views import View

from AccountsManagementApp.models.Transaction import Transaction
from AccountsManagementApp.models.Project import Project


class ReportsView(View):
    def get(self, request):
        transactions = Transaction.objects.all().order_by("-date")
        projects = Project.objects.all()

        # Render the template with the filtered transactions
        return render(
            request,
            "AccountsManagementApp/reports.html",
            {"transactions": transactions, "projects": projects},
        )

AccountsManagementApp/views/transactions.py
from django.shortcuts import render
from django.views import View

from AccountsManagementApp.models.Transaction import Transaction
from AccountsManagementApp.models.Project import Project


class AllTransactionsView(View):
    def get(self, request):
        transactions = Transaction.objects.all().order_by("-date")
        projects = Project.objects.all()

        # Get filter parameters from the request
        project_id = request.GET.get("project")
        start_date = request.GET.get("start_date")
        end_date = request.GET.get("end_date")

        # Apply filters
        if project_id:
            transactions = transactions.filter(project_id=project_id)
        if start_date:
            transactions = transactions.filter(date__gte=start_date)
        if end_date:
            transactions = transactions.filter(date__lte=end_date)

        # Render the template with the filtered transactions
        return render(
            request,
            "AccountsManagementApp/transactions.html",
            {"transactions": transactions, "projects": projects},
        )

FinanceManagementApp/views/dashboard.py
from datetime import datetime, timedelta
from django.views.generic import TemplateView
from dateutil.relativedelta import relativedelta
from django.db.models import Sum, Q
from ..models.Transaction import Transaction
import plotly.graph_objs as go

RECENT_TRANSACTIONS_LIMIT = 10
FINANCIAL_YEAR_START_MONTH = 4
FINANCIAL_YEAR_END_MONTH = 3


class DashboardView(TemplateView):
    """
    A view that displays the dashboard.
    """

    template_name = "FinanceManagementApp/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["recent_transactions"] = (
            Transaction.objects.prefetch_related("project")
            .select_related("project")
            .order_by("-date")[:RECENT_TRANSACTIONS_LIMIT]
        )

        current_datetime = datetime.now()

        context["graph_html_project_wise"] = self.generate_graph_project_wise()

        context["graph_html_this_month"] = self.generate_graph_this_month(
            current_datetime
        )

        context["graph_html_this_year"] = self.generate_graph_this_year(
            current_datetime
        )

        return context

    def get_this_month_dates(self, current_datetime: datetime) -> tuple:
        this_month_start = current_datetime.replace(day=1)
        this_month_end = (current_datetime + relativedelta(months=1)).replace(
            day=1
        ) - timedelta(days=1)
        return this_month_start, this_month_end

    def get_financial_year_dates(self, now: datetime) -> tuple:
        if now.month < FINANCIAL_YEAR_START_MONTH:
            this_year_start = (now - relativedelta(years=1)).replace(
                month=FINANCIAL_YEAR_START_MONTH, day=1
            )
            this_year_end = now.replace(month=FINANCIAL_YEAR_END_MONTH, day=31)
        else:
            this_year_start = now.replace(month=FINANCIAL_YEAR_START_MONTH, day=1)
            this_year_end = (now + relativedelta(years=1)).replace(
                month=FINANCIAL_YEAR_END_MONTH, day=31
            )
        return this_year_start, this_year_end

    def generate_graph_this_month(self, current_datetime):
        """Plot this month's revenue, expense, and profit"""

        this_month_start, this_month_end = self.get_this_month_dates(current_datetime)

        this_month_revenue = (
            Transaction.objects.filter(
                date__gte=this_month_start,
                date__lte=this_month_end,
                transaction_type="Income",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )
        this_month_expense = (
            Transaction.objects.filter(
                date__gte=this_month_start,
                date__lte=this_month_end,
                transaction_type="Expense",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )
        this_month_profit = this_month_revenue - this_month_expense

        # Create a Plotly figure for this month's revenue, expense, and profit
        fig_this_month = go.Figure(
            data=[
                go.Bar(
                    name="Revenue",
                    x=["This Month"],
                    y=[this_month_revenue],
                    text=[f"{this_month_revenue:,}"],
                    textposition="auto",
                ),
                go.Bar(
                    name="Expense",
                    x=["This Month"],
                    y=[this_month_expense],
                    text=[f"{this_month_expense:,}"],
                    textposition="auto",
                ),
                go.Bar(
                    name="Profit",
                    x=["This Month"],
                    y=[this_month_profit],
                    text=[f"{this_month_profit:,}"],
                    textposition="auto",
                ),
            ]
        )
        # Update the layout
        fig_this_month.update_layout(
            title="This Month's Revenue, Expense, and Profit", barmode="group"
        )
        # Convert the figure to HTML
        graph_html_this_month = fig_this_month.to_html(include_plotlyjs="cdn")

        return graph_html_this_month

    def generate_graph_this_year(self, current_datetime):
        """Plot this financial year's revenue, expense, and profit"""

        this_year_start, this_year_end = self.get_financial_year_dates(current_datetime)

        this_year_revenue = (
            Transaction.objects.filter(
                date__gte=this_year_start,
                date__lte=this_year_end,
                transaction_type="Income",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )

        this_year_expense = (
            Transaction.objects.filter(
                date__gte=this_year_start,
                date__lte=this_year_end,
                transaction_type="Expense",
            ).aggregate(total_amount=Sum("amount"))["total_amount"]
            or 0
        )
        this_year_profit = this_year_revenue - this_year_expense

        # Create a Plotly figure
        fig_this_year = go.Figure(
            data=[
                go.Bar(
                    name="Revenue",
                    x=["This Financial Year"],
                    y=[this_year_revenue],
                    text=[f"{this_year_revenue:,}"],
                    textposition="auto",
                ),
                go.Bar(
                    name="Expense",
                    x=["This Financial Year"],
                    y=[this_year_expense],
                    text=[f"{this_year_expense:,}"],
                    textposition="auto",
                ),
                go.Bar(
                    name="Profit",
                    x=["This Financial Year"],
                    y=[this_year_profit],
                    text=[f"{this_year_profit:,}"],
                    textposition="auto",
                ),
            ]
        )

        # Update the layout
        fig_this_year.update_layout(
            title="This Financial Year's Revenue, Expense, and Profit", barmode="group"
        )

        # Convert the figure to HTML
        graph_html_this_year = fig_this_year.to_html(include_plotlyjs="cdn")

        return graph_html_this_year

    def generate_graph_project_wise(self):
        # Plot project-wise income and expense data, 5 most recent by start date
        project_data = (
            Transaction.objects.values("project__name")
            .annotate(
                income=Sum("amount", filter=Q(transaction_type="Income")),
                expense=Sum("amount", filter=Q(transaction_type="Expense")),
            )
            .order_by("project__start_date")
            .reverse()[:5]
        )
        #  list to store profit values
        profit = [data["income"] - data["expense"] for data in project_data]

        # Create a Plotly figure for project-wise income, expense, and profit
        fig = go.Figure(
            data=[
                go.Bar(
                    name="Income",
                    x=[data["project__name"] for data in project_data],
                    y=[data["income"] for data in project_data],
                    text=[f"{data['income']:,}" for data in project_data],
                    textposition="auto",
                ),
                go.Bar(
                    name="Expense",
                    x=[data["project__name"] for data in project_data],
                    y=[data["expense"] for data in project_data],
                    text=[f"{data['expense']:,}" for data in project_data],
                    textposition="auto",
                ),
                go.Bar(
                    name="Profit",
                    x=[data["project__name"] for data in project_data],
                    y=profit,
                    text=[f"{value:,}" for value in profit],
                    textposition="auto",
                ),
            ]
        )

        # Update the layout
        fig.update_layout(
            title="Revenue, Expense, and Profit report for Recent projects",
            barmode="group",
        )

        # Convert the figure to HTML
        graph_html_project_wise = fig.to_html(include_plotlyjs="cdn")

        return graph_html_project_wise

FinanceManagementApp/templates/FinanceManagementApp/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Financial Management App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <a class="navbar-brand ms-4 me-4" href="{% url '' %}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item me-4">
                    <a class="nav-link" href="{% url 'transactions' %}">Transactions</a>
                </li>
                <li class="nav-item me-4">
                    <a class="nav-link" href="{% url 'reports' %}">Reports</a>
                </li>
                <li class="nav-item me-4">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>

</body>

</html>

FinanceManagementApp/templates/FinanceManagementApp/dashboard.html
{% extends 'FinanceManagementApp/base.html' %}

{% block content %}
<div class="container mt-2">
    <div class="card mb-4">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="mb-0">Financials Visualized</h1>
                    <a href="{% url 'reports' %}" class="btn bt-secondary">View Detailed Reports</a>
            </div>
            <div class="row">
                <div class="col-md-6">

                    {{ graph_html_this_month|safe }}

                </div>
                <div class="col-md-6">

                    {{ graph_html_this_year|safe }}

                </div>
            </div>

            {{ graph_html_project_wise|safe }}
        </div>
    </div>

    <!-- Example Data Table -->
    <div class="card mb-4">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="mb-0">Recent Transactions</h1>
                    <a href="{% url 'transactions' %}" class="btn bt-secondary">View All Transactions</a>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Amount</th>
                        <th>Income/Expense Type</th>
                        <th>Project</th>
                        <!-- <th>Description</th> -->
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in recent_transactions %}
                    <tr>
                        <td>{{ transaction.date }}</td>
                        <td>{{ transaction.get_transaction_type_display }}</td>
                        <td>{{ transaction.amount }}</td>
                        <td>{{ transaction.income_expense_type }}</td>
                        <td>{{ transaction.project.name }}</td>
                        <!-- <td>{{ transaction.description }}</td> -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

FinanceManagementApp/templates/FinanceManagementApp/projects_list.html
<!-- project_list.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <div class="container mt-4">
        <h1 class="mb-4">Project List</h1>
        <div class="row">
            {% for project in projects %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.name }}</h5>
                        <p class="card-text">{{ project.description }}</p>
                        <p class="card-text"><small class="text-muted">Status: {{ project.get_status_display }}</small>
                        </p>
                        <p class="card-text"><small class="text-muted">Start Date: {{ project.start_date }}</small></p>
                        <p class="card-text"><small class="text-muted">End Date: {{ project.end_date }}</small></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

FinanceManagementApp/templates/FinanceManagementApp/reports.html
{% extends 'FinanceManagementApp/base.html' %}

{% block content %}


<div class="container mt-2">
    <div class="card mb-4">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="mb-0">Detailed Reports</h1>
                    <!-- <a href="{% url 'reports' %}" class="btn bt-secondary">View Detailed Reports</a> -->
            </div>
            <div class="row">
                <div class="col-md-6">

                    {{ graph_html_this_year_expense|safe }}

                </div>
                <div class="col-md-6">

                    {{ graph_html_this_year_income|safe }}

                </div>
            </div>

            {{ graph_html_project_wise|safe }}
        </div>
    </div>
</div>

{% endblock %}

FinanceManagementApp/templates/FinanceManagementApp/transactions.html
{% extends 'FinanceManagementApp/base.html' %}

{% block content %}
<div class="container mt-4">

    <!-- Add filter form -->
    <form method="get">
        <div class="row g-3">
            <div class="col-md-4">
                <label for="project" class="form-label">Project:</label>
                <select id="project" name="project" class="form-select">
                    <option value="">All Projects</option>
                    {% for project in projects %}
                    <option value="{{ project.id }}">{{ project.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-4">
                <label for="start_date" class="form-label">Start Date:</label>
                <input type="date" id="start_date" name="start_date" class="form-control">
            </div>
            <div class="col-md-4">
                <label for="end_date" class="form-label">End Date:</label>
                <input type="date" id="end_date" name="end_date" class="form-control">
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2 mb-2">Filter</button>
    </form>
    <!-- Transaction table -->
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Amount</th>
                <th>Income/Expense Type</th>
                <th>Project</th>
                <!-- <th>Description</th> -->
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.date }}</td>
                <td>{{ transaction.get_transaction_type_display }}</td>
                <td>{{ transaction.amount }}</td>
                <td>{{ transaction.income_expense_type }}</td>
                <td>{{ transaction.project.name }}</td>
                <!-- <td data-toggle="tooltip" data-placement="top" title="{{ transaction.description }}">{{
                    transaction.description|truncatechars:10 }}</td> -->
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}